"""Golden-snapshot spec: pins the entire CLI surface (every command's option identity).

Walks ``gilt.cli.app.app`` via ``typer.main.get_command`` and, for every registered
command, emits a sorted record of every option's ``(command_name, param_name, opts,
secondary_opts, type_name, required, default, help)``. Asserts the collected surface
equals ``EXPECTED_SURFACE`` below — a literal snapshot generated once by running the
collector against the untouched tree and pasting the real output.

This is the regression net for the option-vocabulary consolidation (see
``_options.py``): as long as this spec passes, the CLI's user-visible flags, short
options, types, requiredness, defaults, and help text are unchanged, no matter how
much the registration modules are refactored internally.
"""

from __future__ import annotations

import typer.main

from gilt.cli.app import app

# Generated once from `typer.main.get_command(app)` against the untouched tree.
# Sorted by (command_name, param_name). Do not hand-edit — regenerate via the
# collector in `collect_cli_surface()` if the CLI surface intentionally changes.
EXPECTED_SURFACE: list[tuple] = [
    (
        "audit-ml",
        "filter_pattern",
        ("--filter", "-f"),
        (),
        "StringParamType",
        False,
        None,
        "Regex pattern to filter descriptions",
    ),
    (
        "audit-ml",
        "limit",
        ("--limit", "-n"),
        (),
        "IntParamType",
        False,
        20,
        "Maximum examples to show",
    ),
    (
        "audit-ml",
        "mode",
        ("--mode", "-m"),
        (),
        "StringParamType",
        False,
        "summary",
        "Audit mode: summary, training, predictions, or features",
    ),
    (
        "auto-categorize",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        False,
        None,
        "Account ID to filter (omit for all accounts)",
    ),
    (
        "auto-categorize",
        "confidence",
        ("--confidence", "-c"),
        (),
        "FloatRange",
        False,
        0.7,
        "Minimum confidence threshold (0.0-1.0)",
    ),
    (
        "auto-categorize",
        "explain",
        ("--explain",),
        (),
        "BoolParamType",
        False,
        False,
        "Print top-3 category candidates with calibrated confidences",
    ),
    (
        "auto-categorize",
        "interactive",
        ("--interactive", "-i"),
        (),
        "BoolParamType",
        False,
        False,
        "Enable interactive review mode",
    ),
    (
        "auto-categorize",
        "limit",
        ("--limit", "-n"),
        (),
        "IntRange",
        False,
        None,
        "Max number of transactions to auto-categorize",
    ),
    (
        "auto-categorize",
        "min_samples",
        ("--min-samples",),
        (),
        "IntRange",
        False,
        5,
        "Minimum samples per category for training",
    ),
    (
        "auto-categorize",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "backfill-events",
        "budget_projections_db",
        ("--budget-projections-db",),
        (),
        "TyperPath",
        False,
        None,
        "Path to budget projections database (advanced override)",
    ),
    (
        "backfill-events",
        "events_db",
        ("--event-store",),
        (),
        "TyperPath",
        False,
        None,
        "Path to event store database (advanced override)",
    ),
    (
        "backfill-events",
        "projections_db",
        ("--projections-db",),
        (),
        "TyperPath",
        False,
        None,
        "Path to transaction projections database (advanced override)",
    ),
    (
        "backfill-events",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Actually write events (default: dry-run)",
    ),
    (
        "budget",
        "category",
        ("--category", "-c"),
        (),
        "StringParamType",
        False,
        None,
        "Filter to specific category",
    ),
    (
        "budget",
        "month",
        ("--month", "-m"),
        (),
        "IntParamType",
        False,
        None,
        "Month to report (1-12, requires --year)",
    ),
    (
        "budget",
        "year",
        ("--year", "-y"),
        (),
        "IntParamType",
        False,
        None,
        "Year to report (default: current year)",
    ),
    (
        "categorize",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        False,
        None,
        "Account ID (omit to categorize across all accounts)",
    ),
    (
        "categorize",
        "amount",
        ("--amount", "-m"),
        (),
        "FloatParamType",
        False,
        None,
        "Exact amount to match (batch mode)",
    ),
    (
        "categorize",
        "category",
        ("--category", "-c"),
        (),
        "StringParamType",
        False,
        None,
        "Category name (supports 'Category:Subcategory' syntax)",
    ),
    (
        "categorize",
        "desc_prefix",
        ("--desc-prefix", "-p"),
        (),
        "StringParamType",
        False,
        None,
        "Description prefix to match (batch mode, case-insensitive)",
    ),
    (
        "categorize",
        "description",
        ("--description", "-d"),
        (),
        "StringParamType",
        False,
        None,
        "Exact description to match (batch mode)",
    ),
    (
        "categorize",
        "from_stdin",
        ("--from-stdin",),
        (),
        "BoolParamType",
        False,
        False,
        "Read '<txid-prefix> <category>' pairs from stdin",
    ),
    (
        "categorize",
        "pattern",
        ("--pattern",),
        (),
        "StringParamType",
        False,
        None,
        "Regex pattern to match description (batch mode, case-insensitive)",
    ),
    (
        "categorize",
        "subcategory",
        ("--subcategory", "-s"),
        (),
        "StringParamType",
        False,
        None,
        "Subcategory name (alternative to colon syntax)",
    ),
    (
        "categorize",
        "txid",
        ("--txid", "-t"),
        (),
        "StringParamType",
        False,
        None,
        "Transaction ID prefix (single mode)",
    ),
    (
        "categorize",
        "txid_file",
        ("--txid-file",),
        (),
        "TyperPath",
        False,
        None,
        "File of '<txid-prefix> <category>' pairs to apply in one batch",
    ),
    (
        "categorize",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "categorize",
        "yes",
        ("--yes", "-y"),
        (),
        "BoolParamType",
        False,
        False,
        "Assume 'yes' for all confirmations in batch mode",
    ),
    (
        "category",
        "add",
        ("--add",),
        (),
        "StringParamType",
        False,
        None,
        "Add a new category (supports 'Category:Subcategory')",
    ),
    ("category", "amount", ("--amount",), (), "FloatParamType", False, None, "Budget amount"),
    (
        "category",
        "description",
        ("--description",),
        (),
        "StringParamType",
        False,
        None,
        "Description for new category",
    ),
    (
        "category",
        "force",
        ("--force",),
        (),
        "BoolParamType",
        False,
        False,
        "Skip confirmations when removing used categories",
    ),
    (
        "category",
        "period",
        ("--period",),
        (),
        "StringParamType",
        False,
        "monthly",
        "Budget period (monthly or yearly)",
    ),
    ("category", "remove", ("--remove",), (), "StringParamType", False, None, "Remove a category"),
    (
        "category",
        "set_budget",
        ("--set-budget",),
        (),
        "StringParamType",
        False,
        None,
        "Set budget for a category",
    ),
    (
        "category",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "duplicates",
        "amount_tolerance",
        ("--amount-tolerance",),
        (),
        "FloatParamType",
        False,
        0.001,
        "Acceptable difference in amounts",
    ),
    (
        "duplicates",
        "interactive",
        ("--interactive", "-i"),
        (),
        "BoolParamType",
        False,
        False,
        "Enable interactive mode to confirm/deny each duplicate",
    ),
    (
        "duplicates",
        "max_days_apart",
        ("--max-days",),
        (),
        "IntParamType",
        False,
        1,
        "Maximum days between potential duplicates",
    ),
    (
        "duplicates",
        "min_confidence",
        ("--min-confidence",),
        (),
        "FloatParamType",
        False,
        0.0,
        "Minimum confidence threshold to display (0.0-1.0)",
    ),
    (
        "duplicates",
        "model",
        ("--model",),
        (),
        "StringParamType",
        False,
        "qwen3.6:35b-a3b-coding-nvfp4",
        "Ollama model for LLM duplicate detection",
    ),
    (
        "duplicates",
        "use_llm",
        ("--llm",),
        (),
        "BoolParamType",
        False,
        False,
        "Use LLM instead of ML (slower, no training needed)",
    ),
    (
        "history",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        False,
        None,
        "Restrict to this account ID",
    ),
    (
        "history",
        "date_from",
        ("--date-from",),
        (),
        "StringParamType",
        False,
        None,
        "Start date (YYYY-MM-DD, inclusive)",
    ),
    (
        "history",
        "date_to",
        ("--date-to",),
        (),
        "StringParamType",
        False,
        None,
        "End date (YYYY-MM-DD, inclusive)",
    ),
    (
        "history",
        "include_uncategorized",
        ("--include-uncategorized",),
        (),
        "BoolParamType",
        False,
        False,
        "Include uncategorized transactions",
    ),
    (
        "history",
        "limit",
        ("--limit", "-n"),
        (),
        "IntParamType",
        False,
        10,
        "Maximum result rows (default 10)",
    ),
    (
        "infer-rules",
        "apply",
        ("--apply",),
        (),
        "BoolParamType",
        False,
        False,
        "Apply rules to uncategorized transactions",
    ),
    (
        "infer-rules",
        "export",
        ("--export",),
        (),
        "StringParamType",
        False,
        None,
        "Export rules to JSON file",
    ),
    (
        "infer-rules",
        "min_confidence",
        ("--min-confidence",),
        (),
        "FloatRange",
        False,
        0.9,
        "Minimum consistency to infer a rule",
    ),
    (
        "infer-rules",
        "min_evidence",
        ("--min-evidence",),
        (),
        "IntRange",
        False,
        3,
        "Minimum categorizations to infer a rule",
    ),
    (
        "infer-rules",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "ingest",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "ingest-receipts",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        False,
        None,
        "Limit matching to this account",
    ),
    (
        "ingest-receipts",
        "interactive",
        ("--interactive", "-i"),
        (),
        "BoolParamType",
        False,
        False,
        "Interactively resolve ambiguous matches",
    ),
    (
        "ingest-receipts",
        "source",
        ("--source",),
        (),
        "TyperPath",
        True,
        None,
        "Root directory containing receipt JSON files (recursive scan)",
    ),
    (
        "ingest-receipts",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "ingest-receipts",
        "year",
        ("--year", "-y"),
        (),
        "IntParamType",
        False,
        None,
        "Only process receipts from this year",
    ),
    (
        "mark-duplicate",
        "duplicate_txid",
        ("--duplicate", "-d"),
        (),
        "StringParamType",
        True,
        None,
        "Transaction ID to mark as duplicate (8+ char prefix)",
    ),
    (
        "mark-duplicate",
        "primary_txid",
        ("--primary", "-p"),
        (),
        "StringParamType",
        True,
        None,
        "Transaction ID to keep (8+ char prefix)",
    ),
    (
        "mark-duplicate",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "migrate-to-events",
        "budget_projections_db",
        ("--budget-projections-db",),
        (),
        "TyperPath",
        False,
        None,
        "Path to budget projections database (advanced override)",
    ),
    (
        "migrate-to-events",
        "events_db",
        ("--event-store",),
        (),
        "TyperPath",
        False,
        None,
        "Path to event store database (advanced override)",
    ),
    (
        "migrate-to-events",
        "force",
        ("--force",),
        (),
        "BoolParamType",
        False,
        False,
        "Overwrite existing event store",
    ),
    (
        "migrate-to-events",
        "projections_db",
        ("--projections-db",),
        (),
        "TyperPath",
        False,
        None,
        "Path to transaction projections database (advanced override)",
    ),
    (
        "migrate-to-events",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Actually perform migration (default: dry-run)",
    ),
    (
        "note",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        True,
        None,
        "Account ID containing the transaction (e.g., MYBANK_CHQ)",
    ),
    (
        "note",
        "amount",
        ("--amount", "-m"),
        (),
        "FloatParamType",
        False,
        None,
        "Exact amount to match (batch mode)",
    ),
    (
        "note",
        "desc_prefix",
        ("--desc-prefix", "-p"),
        (),
        "StringParamType",
        False,
        None,
        "Description prefix to match (batch mode, case-insensitive)",
    ),
    (
        "note",
        "description",
        ("--description", "-d"),
        (),
        "StringParamType",
        False,
        None,
        "Exact description to match (batch mode)",
    ),
    (
        "note",
        "note_text",
        ("--note", "-n"),
        (),
        "StringParamType",
        True,
        None,
        "Note text to set on the transaction(s)",
    ),
    (
        "note",
        "pattern",
        ("--pattern",),
        (),
        "StringParamType",
        False,
        None,
        "Regex pattern to match description (batch mode, case-insensitive)",
    ),
    (
        "note",
        "txid",
        ("--txid", "-t"),
        (),
        "StringParamType",
        False,
        None,
        "Transaction ID prefix (TxnID8 as shown in tables)",
    ),
    (
        "note",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "note",
        "yes",
        ("--yes", "-y", "-r"),
        (),
        "BoolParamType",
        False,
        False,
        "Assume 'yes' for all confirmations in batch mode",
    ),
    (
        "prompt-stats",
        "generate_update",
        ("--generate-update", "-g"),
        (),
        "BoolParamType",
        False,
        False,
        "Generate a new PromptUpdated event based on learned patterns",
    ),
    (
        "rebuild-projections",
        "events_db",
        ("--events-db",),
        (),
        "TyperPath",
        False,
        None,
        "Path to events database (advanced override)",
    ),
    (
        "rebuild-projections",
        "from_scratch",
        ("--from-scratch",),
        (),
        "BoolParamType",
        False,
        False,
        "Delete existing projections and rebuild from all events",
    ),
    (
        "rebuild-projections",
        "incremental",
        ("--incremental",),
        (),
        "BoolParamType",
        False,
        False,
        "Only apply new events since last rebuild (default behavior)",
    ),
    (
        "rebuild-projections",
        "projections_db",
        ("--projections-db",),
        (),
        "TyperPath",
        False,
        None,
        "Path to projections database (advanced override)",
    ),
    (
        "recategorize",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        False,
        None,
        "Restrict selection to this account ID",
    ),
    (
        "recategorize",
        "amount_eq",
        ("--amount-eq",),
        (),
        "FloatParamType",
        False,
        None,
        "Exact signed amount to match",
    ),
    (
        "recategorize",
        "amount_max",
        ("--amount-max",),
        (),
        "FloatParamType",
        False,
        None,
        "Maximum signed amount (inclusive)",
    ),
    (
        "recategorize",
        "amount_min",
        ("--amount-min",),
        (),
        "FloatParamType",
        False,
        None,
        "Minimum signed amount (inclusive)",
    ),
    (
        "recategorize",
        "date_from_str",
        ("--date-from",),
        (),
        "StringParamType",
        False,
        None,
        "Start date (YYYY-MM-DD, inclusive)",
    ),
    (
        "recategorize",
        "date_to_str",
        ("--date-to",),
        (),
        "StringParamType",
        False,
        None,
        "End date (YYYY-MM-DD, inclusive)",
    ),
    (
        "recategorize",
        "desc_prefix",
        ("--desc-prefix", "-p"),
        (),
        "StringParamType",
        False,
        None,
        "Description prefix filter (case-insensitive)",
    ),
    (
        "recategorize",
        "from_cat",
        ("--from",),
        (),
        "StringParamType",
        False,
        None,
        "Original category name (supports 'Category:Subcategory')",
    ),
    (
        "recategorize",
        "fy",
        ("--fy",),
        (),
        "StringParamType",
        False,
        None,
        "Fiscal year to filter (Nov 1 – Oct 31). Accepts FY25, fy25, FY2025.",
    ),
    (
        "recategorize",
        "pattern",
        ("--pattern",),
        (),
        "StringParamType",
        False,
        None,
        "Regex pattern filter on descriptions",
    ),
    (
        "recategorize",
        "to_cat",
        ("--to",),
        (),
        "StringParamType",
        True,
        None,
        "New category name (supports 'Category:Subcategory')",
    ),
    (
        "recategorize",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "receipts",
        "by_account",
        ("--by-account",),
        (),
        "BoolParamType",
        False,
        False,
        "Group by account_id instead of subcategory",
    ),
    (
        "receipts",
        "category",
        ("--category", "-c"),
        (),
        "StringParamType",
        False,
        "Mojility",
        "Category to report on (default: Mojility)",
    ),
    (
        "receipts",
        "fy",
        ("--fy",),
        (),
        "StringParamType",
        False,
        None,
        "Fiscal year filter (Nov 1 – Oct 31). Accepts FY25, fy25, FY2025.",
    ),
    (
        "receipts",
        "missing",
        ("--missing",),
        (),
        "BoolParamType",
        False,
        False,
        "List individual transactions without receipts instead of the summary table",
    ),
    (
        "reingest",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        True,
        None,
        "Account ID to reingest (e.g., MYBANK_CC)",
    ),
    (
        "reingest",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "report",
        "month",
        ("--month", "-m"),
        (),
        "IntParamType",
        False,
        None,
        "Month to report (1-12, requires --year)",
    ),
    (
        "report",
        "output",
        ("--output", "-o"),
        (),
        "TyperPath",
        False,
        None,
        "Output path (without extension, default: reports/budget_report_YYYY[-MM])",
    ),
    (
        "report",
        "write",
        ("--write",),
        (),
        "BoolParamType",
        False,
        False,
        "Persist changes (default: dry-run)",
    ),
    (
        "report",
        "year",
        ("--year", "-y"),
        (),
        "IntParamType",
        False,
        None,
        "Year to report (default: current year)",
    ),
    (
        "show",
        "txid",
        ("--txid", "-t"),
        (),
        "StringParamType",
        True,
        None,
        "Transaction ID prefix (8+ characters)",
    ),
    (
        "skill-init",
        "force",
        ("--force",),
        (),
        "BoolParamType",
        False,
        False,
        "Bypass version guard (overrides the refusal to overwrite a newer installed version)",
    ),
    (
        "skill-init",
        "global_install",
        ("--global",),
        (),
        "BoolParamType",
        False,
        False,
        "Install to ~/.claude/skills/gilt/ (global)",
    ),
    (
        "skill-init",
        "json_output",
        ("--json",),
        (),
        "BoolParamType",
        False,
        False,
        "Emit machine-readable JSON output to stdout",
    ),
    (
        "status",
        "fy",
        ("--fy",),
        (),
        "StringParamType",
        False,
        None,
        "Fiscal year for Mojility columns (Nov 1 – Oct 31). Accepts FY25, fy25, FY2025.",
    ),
    (
        "status",
        "stale_threshold",
        ("--stale-threshold",),
        (),
        "IntRange",
        False,
        14,
        "Days since latest transaction before account is flagged stale",
    ),
    (
        "summary",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        False,
        None,
        "Account ID to filter",
    ),
    (
        "summary",
        "category",
        ("--category", "-c"),
        (),
        "StringParamType",
        False,
        None,
        "Drill into one category's subcategories",
    ),
    (
        "summary",
        "fy",
        ("--fy",),
        (),
        "StringParamType",
        False,
        None,
        "Fiscal year (Nov 1 – Oct 31). Accepts FY25, fy25, FY2025.",
    ),
    (
        "summary",
        "include_uncategorized",
        ("--include-uncategorized",),
        (),
        "BoolParamType",
        False,
        False,
        "Include rows where category is null",
    ),
    (
        "summary",
        "year",
        ("--year", "-y"),
        (),
        "IntParamType",
        False,
        None,
        "Calendar year (default: current)",
    ),
    (
        "uncategorized",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        False,
        None,
        "Account ID to filter (omit for all accounts)",
    ),
    (
        "uncategorized",
        "fy",
        ("--fy",),
        (),
        "StringParamType",
        False,
        None,
        "Fiscal year to filter (Nov 1 – Oct 31). Accepts FY25, fy25, FY2025.",
    ),
    (
        "uncategorized",
        "limit",
        ("--limit", "-n"),
        (),
        "IntRange",
        False,
        None,
        "Max number of transactions to show",
    ),
    (
        "uncategorized",
        "min_amount",
        ("--min-amount",),
        (),
        "FloatParamType",
        False,
        None,
        "Minimum absolute amount to include",
    ),
    (
        "uncategorized",
        "year",
        ("--year", "-y"),
        (),
        "IntParamType",
        False,
        None,
        "Calendar year to filter",
    ),
    (
        "ytd",
        "account",
        ("--account", "-a"),
        (),
        "StringParamType",
        True,
        None,
        "Account ID to display (e.g., MYBANK_CHQ)",
    ),
    (
        "ytd",
        "compare",
        ("--compare",),
        (),
        "BoolParamType",
        False,
        False,
        "Show enriched transactions with bank description and vendor side by side",
    ),
    (
        "ytd",
        "default_currency",
        ("--default-currency",),
        (),
        "StringParamType",
        False,
        None,
        "Fallback currency if missing in legacy rows (e.g., CAD)",
    ),
    (
        "ytd",
        "include_duplicates",
        ("--include-duplicates",),
        (),
        "BoolParamType",
        False,
        False,
        "Include transactions marked as duplicates",
    ),
    (
        "ytd",
        "limit",
        ("--limit", "-n"),
        (),
        "IntRange",
        False,
        None,
        "Max number of rows to show (after sorting)",
    ),
    (
        "ytd",
        "raw",
        ("--raw",),
        (),
        "BoolParamType",
        False,
        False,
        "Show original bank descriptions instead of vendor names",
    ),
    (
        "ytd",
        "year",
        ("--year", "-y"),
        (),
        "IntParamType",
        False,
        None,
        "Year to filter (defaults to current year)",
    ),
]


def collect_cli_surface() -> list[tuple]:
    """Walk the live Typer app and collect every command's option identity.

    Returns a sorted list of ``(command_name, param_name, opts, secondary_opts,
    type_name, required, default, help)`` tuples — one per registered option
    across every command in ``gilt.cli.app.app``.
    """
    root = typer.main.get_command(app)
    records: list[tuple] = []

    def walk(command, command_name: str | None) -> None:
        if hasattr(command, "commands"):
            for name, sub in command.commands.items():
                walk(sub, name)
            return
        for param in command.params:
            if getattr(param, "param_type_name", None) != "option":
                continue
            records.append(
                (
                    command_name,
                    param.name,
                    tuple(param.opts),
                    tuple(param.secondary_opts),
                    type(param.type).__name__,
                    param.required,
                    param.default,
                    param.help,
                )
            )

    walk(root, None)
    return sorted(records)


class DescribeCliSurface:
    def it_should_match_the_pinned_golden_snapshot(self):
        assert collect_cli_surface() == sorted(EXPECTED_SURFACE)


__all__ = ["collect_cli_surface", "EXPECTED_SURFACE"]
